# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce27a0e195bd8d51c916109eab3dd4bce4db32458c4c481635e74c998a0e6ba56a7bed7d84c46fd8dd57e5c824e69332d4f8a3e38045f0890af4ff253184e5a2

test:
  secret_key_base: b59f1c66baeef1e3d4b9edf85c3aa7366ab4dc179da3a02387d6639748b095c653248d0152c6c4c87487c44a4a591425dd3e7e35826251c943b7c181b8f9c51c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
